### PR TITLE
brynn.as Random Event 

### PR DESCRIPTION
**Pull request by rotweiller92**
Ok, so first here is a summary:
1.Never triggered the event.
2.Stumbled upon it while checking the code for how the Auto-enter works (came from the wiki)
3.Not sure if intended or not.(Most probably not intended)

So, on the function call brynnRandomBarnEventFunc() there is a 
if(cock){
...
    if(vagina){
    }
}
instead of 
if(cock){ 
...
}
if(vagina){
...
}

All the additions and deletions are tabs (not sure if it was necessary)

### CODE REVIEW

**Comment by Jacques00** [comment]
To update for new functions, you might want to change all "pc.isCrotchGarbed()" checks to "!pc.isCrotchExposed()", just so it makes sense in context (3 instances).

**Comment by rotweiller92** [comment]
Ain't following that much the functions used, just stumbled on the ifs.

**Comment by rotweiller92** [comment]
Just to be sure, is Garbed the complementary of Exposed? Is it deprecated?

**Comment by Jacques00** [comment]
Somewhat. Garbed checks if the character is clothed in that area, whereas the Exposed check whether cloth is covering that part, and if it is, if that piece of clothing is exposing that body part. Garbed shouldn't be depreciated--Exposed is just more specific a check, especially for sentences that talk about rubbing worn material against a supposedly exposed body part.

Garbed checks are primarily used like the Nude check, where undressing comes into play, so this can also apply for undressing exposed clothing as well. There needs to be a review of all scenes to include the newer Exposed check-- but in time, I suppose. I just suggested it for your edit so you can knock out two birds with one stone.

**Comment by rotweiller92** [comment]
Ok, now i understood the meanings.
Think I'm gonna leave the pull as it is.
86 cases are a lot, not sure if fenoxo would want a pull request with like 90 commits from a new user.
Would be honored, but these are more of case by case meanings, rather then coding. 
The double checking would still be needed by an admin.
So probably just gonna leave it as a new open issue, or they probably already know that the addition of the exposed function meant revisiting all cases (especially the items)

**Comment by Jacques00** [comment]
Ah, the changes you have up for this pull request is fine, no worries. 

I just mentioned the other Garbed/Exposed cases as a to-do overlook more than anything else. I definitely wouldn't want to hold you accountable for all the needed changes. I'll probably rummage through the scripts and make the Garbed/Exposed changes when/if I have the time for it.

**Pull request merged**
