### PR TITLE
Minor Fixes and Updates

### PR DESCRIPTION
**Pull request by Jacques00**
* Correct author credit for a new Lactaid item.
* Removed references to "queen" and "ovipositor" for Burt's mentions of zil.
* Burt is in possible need of revision to make sure zil culture and species are consistent in the game universe.
* MinoCharge has chance to add lower-body beefiness.

### CODE REVIEW

**Comment by Fenoxo** [comment]
Why the changes to burt?

**Comment by Jacques00** [comment]
Ah, just some minor inconsistencies with female zil (mentions queens and ovipositors when that is not the case). But Burt content might need some review in case there are other inconsistencies--not really a major flaw though, but just a forecast if there are similar reports.

**Comment by Fenoxo** [comment]
Fair enough. I was looking at having a Taivra-like queen as ruler of the most local village to match up to Burt's story if I ever came back to Mhen'ga. Something special had to happen to the poor guy to give him a honey-leaking butt.

**Comment by Jacques00** [comment]
Cool, I like that idea. Leaving it ambiguous from Burt's explanation might be the best course of action so the player can be pleasantly surprised to run into the event if and when it happens (which I hope it does  : P  ).

**Pull request merged**
