### PR TITLE
Implementation of residential deck on Tavros + NPCs Aina and Fyn

### PR DESCRIPTION
**Pull request by Nachte**
First implementation of residential deck on Tavros (texts by JimTermic)

Includes:
- New rooms (accessed by going up in the elevator on Tavros
- Notice board in one of the rooms with messags from residents
- NPCs Fyn + Aina

### CODE REVIEW

**Comment by Fenoxo** [comment]
Looks like you did pretty good work here. Gonna merge it and review more in depth for balance and such

**Comment by Fenoxo** [comment]
Looks like Dialogue isn't marked up properly with italics.

Also the centaur girl's event should proc when you walk into the room. Having a button labelled "centaur" with no description of the character being there is hella weird.

I'm addressing both right meow.

**Comment by Nachte** [comment]
Yeah, my mistake. I must have missed that really all spoken text is supposed to be put in italics. For Aina I just stuck with what was in the docs. Since she vanishes when the player refuses to help her it seemed to make sense to make meeting her optional, but I agree... it makes more sense from a mechanical point of view to trigger it immediately because of that heat stuff. 

You could have let me know though - I wouldn't have minded to fix either.

**Comment by Fenoxo** [comment]
I needed to review it either way. Any reason you didn't do the other
residential deck person?

**Comment by Nachte** [comment]
There were a lot of comments in the last doc, some of which I wasn't sure were resolved. So it felt incomplete in comparison. And since I wasn't sure what your policy on contributed code is I wanted to keep the commit more manageable. 

I can poke Nonesuch though, ask about the comments, and throw up a new pull request in the comming days.

**Comment by Fenoxo** [comment]
Sounds good to me. Maybe I'll get to work on Emmy tomorrow.

**Comment by Nachte** [comment]
Awesome! Looking forward to it.

**Pull request merged**
